### ISSUE TITLE
Registration page was moved ?

### ISSUE THREAD

**Issue by martinchristen** [BaselHack/BaselHack.github.io#14]
It seems the registration page moved to https://www.baselarea.swiss/de/baselarea-swiss/channels/innovation-events/2017/10/BaselHack-the-hackathon-for-the-Basel-region.html

The one linked at www.baselhack.ch (and on social media like Twitter) is not working anymore and needs update...

Or is it possible to still use the old one and redirect ? https://www.baselarea.swiss/de/baselarea-swiss/channels/innovation-events/2017/10/baselhack-der-hackathon-fuer-die-region-basel.html

@Brenzikofer @culmat

**Comment by teddybeaker** [comment]
Thanks @martinchristen 

I changed the redirect on production manually, since changes on test.baselhack.ch are pending. Added it to git too, so the change won't be overwritten when we move them to production.

@Brenzikofer: if the URL changes again please make sure someone updates the redirect too at the same moment.

**Comment by Brenzikofer** [comment]
danke martin,
wir haben engl aufgeschaltet - deum bitte anmelderformular aendern auf baselhack...
danke thomas

Von meinem iPhone gesendet

> Am 19.08.2017 um 11:36 schrieb Martin Christen <notifications@github.com>:
> 
> 2017
